apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mysqlstorage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate
reclaimPolicy: Delete
allowVolumeExpansion: True
